# ENV['BERKSHELF_PATH'] = "D:\.berkshelf"
ENV['BERKSHELF_PATH'] = "/Users/ak/.berkshelf"
source "https://supermarket.getchef.com"

cookbook 'chef-pgbadger-latest', '0.1.0', github: 'kogitant/chef-pgbadger-latest', protocol: 'ssh'

metadata
